In [45]:
import requests as http
import pandas as pd

url = 'https://api.github.com/repos/pandas-dev/pandas/issues'
# return json
res = http.get(url, timeout=10, verify=False)
jsonData = res.json()

df = pd.DataFrame(jsonData,columns=['number'])
df.head()

c:\Users\ahmed\AppData\Local\Programs\Python\Python313\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.github.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

   number
0   65274
1   65273
2   65272
3   65270
4   65268

In [50]:
first_item = pd.DataFrame([jsonData[0]])

first_item.head()

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,type,active_lock_reason,draft,pull_request,body,closed_by,reactions,timeline_url,performed_via_github_app,state_reason
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/65274,4286243773,PR_kwDOAA0YD87TfyLi,65274,ref:Avoid state mutation in FrameApply.agg by ...,...,None,None,True,{'url': 'https://api.github.com/repos/pandas-d...,\r\n- [x] [Tests added and passed](https://pan...,None,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,None,None